exclude_patterns:
  - "config/"
  - "coverage/"
  - "mirage/"
  - "public/"
  - "tests/"
  - "vendor/"
  - "**/node_modules/"
  - "package.json"
  - "ember-cli-build.js"
  - "fastboot.js"
  - "testem.js"
  - "README.md"