version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.10-browsers
      environment:
        JOBS: 2

jobs:
  install:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install node dependencies
          command: |
            if [ ! -d node_modules ]; then
              yarn --pure-lockfile
            fi
      - save_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  test:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: yarn test

  deploy:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - add_ssh_keys:
          fingerprints:
            - "08:eb:03:31:44:a6:ba:ea:33:11:ef:36:7a:5e:15:22"
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "deploy@circleci"
            git config --global user.name "deploy"
            npx ember deploy production

workflows:
  version: 2
  install-test-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
